name: Rust Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install grcov
        run: cargo install grcov

      - name: Install llvm-tools
        run: rustup component add llvm-tools-preview

      - name: Generate Code Coverage
        run: |
          cd core
          mkdir -p target/coverage
          export RUSTFLAGS="-Cinstrument-coverage"
          export LLVM_PROFILE_FILE="target/coverage/coverage-%p-%m.profraw"
          cargo test
          grcov target/coverage --binary-path target/debug -s . -t cobertura -o target/coverage/coverage.xml --keep-only 'src/*' --output-types cobertura

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./target/coverage/cobertura.xml
          fail_ci_if_error: true
